Gr44MVCEmpty/Models/DarthVader.cs
namespace Gr44MVCEmpty.Models
{
    public class DarthVader
    {
        public static string TestFever(double temp)
        {
            return(temp > 37)? "Doctor Vader says you have fever...have a cookie": "Doctor Vader says you don't have any fever...so no cookie";
        }
    }
}

Gr44MVCEmpty/Controllers/DarthVaderController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gr44MVCEmpty.Controllers
{
    public class DarthVaderController : Controller
    {

        [HttpGet]
        public IActionResult TestForFever(double temp)
        {

            if (temp != 0)
            {
                ViewBag.Msg = Models.DarthVader.TestFever(temp);
                return View();
            }
            else { 
                ViewBag.Msg= "Please enter your temperature and then hit Submit";
                return View(); 
            }
              
        }
        
        [HttpGet]
   
        public IActionResult TestFever()
        {
            return View();
        }
    }
}

Gr44MVCEmpty/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gr44MVCEmpty.Controllers
{
    public class DemoController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PreferdLanguageCookie()
        {
            string? lang = Request.Cookies["PrefLang"];// read the cookie
            if (!string.IsNullOrEmpty(lang))
            {
                ViewBag.Lang = lang;
            }
            return View();
        }
        public IActionResult SetLanguageCookie(string lang)
        {

            if (!string.IsNullOrWhiteSpace(lang))
            {
                //Add cookie to Response object
                CookieOptions option = new CookieOptions();
                option.Expires = DateTime.Now.AddMinutes(1);
                Response.Cookies.Append("PrefLang", lang, option);
            }
            return RedirectToAction(nameof(PreferdLanguageCookie));
        }


    }

}

Gr44MVCEmpty/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gr44MVCEmpty.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Contact()
        {
            return View();
        }
    }
}

Gr44MVCEmpty/Views/DarthVader/TestFever.cshtml
@{
    ViewData["Title"] = "Test Fever";
}
<h1> Welcome to Doctor Vader</h1>


<a asp-action="TestForFever"> Check temp</a>
@Html.ActionLink("Go to","TestForFever","DarthVader")

Gr44MVCEmpty/Views/DarthVader/TestForFever.cshtml
@{
    ViewData["Title"] = "Test For Fever";
}

<div class="container">
    <h2>Doctor Vader Checking out your temp</h2>
    <div class="wrapper">
        <h3>Fever check</h3>
        <form asp-action="TestForFever"asp-controller="DarthVader" method="post">

            <input type="number" name="temp" value="" 
                placeholder="Enter your body temperature" min="0" max="100" step="1" />
                <button type="submit">Submit</button>

                <p>
                    @if(ViewBag.Msg != null)
                    {@ViewBag.Msg}
                </p>
        </form>

    </div>

</div>

Gr44MVCEmpty/Views/Demo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Demo Index</h1>




<a asp-action="PreferdLanguageCookie">Preferd Language Cookie</a>

Gr44MVCEmpty/Views/Demo/PreferdLanguageCookie.cshtml
@{
    ViewData["Title"] = "Preferd Language Cookie";
}

<h1>Preferd Language Cookie</h1>
<p>Save so i don´t need to set it every time i visit this page </p>

<p>Current language: @ViewBag.Lang</p>
<form asp-action="SetLanguageCookie" method="post">
    <select name="Lang">
          
        <option value="swe">Swe</option>
        <option value="en">Eng</option>
        <option value="ro">Ro</option>
         <option value="fr">FR</option>

    </select>
       <button type="submit">Save language preferense</button>
</form>

Gr44MVCEmpty/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Contact us</h1>

<dl>
    <dt> Name:</dt>
    <dd>Åsa Jonsson</dd>
    <dt> Email:</dt>
    <dd>asa.jonsson@lexicon.se</dd>


</dl>

Gr44MVCEmpty/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<h1>Welcome Gr 44</h1>

Gr44MVCEmpty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <h3>Logo</h3>
        <nav>
            <ul>
                <li>
                    <a asp-action="Index"asp-controller="Home">Home</a>
                </li>
                <li>
                    <a asp-controller="DarthVader" asp-action="TestFever">Doctor Vader</a>
                </li>
                 <li>
                    <a asp-action="Contact"asp-controller="Home">Contact</a>
                </li>
                <li>
                    @Html.ActionLink("Demo page","Index","Demo")
                </li>

            </ul>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer>
        <span>&copy; Lexicon</span>
    </footer>
</body>
</html>